update to tko
JuliaGizmos/Knockout.jl pull request #14
Opened 2019-03-29 16:33 UTC by piever

2019-03-29 19:35 UTC, twavv requested changes
I think the JS-lambda change you're proposing is breaking.

```julia
template = dom"button"(
    "{{message}}",
    attributes=Dict(
        # This is broken.
        "data-bind" => "click: () => this.message('goodbye!')",
        # This works though.
        # "data-bind" => "click: function(){ this.message('goodbye!') }",
    ),
)
message = Observable{String}("Hello!")
knockout(template, [:message=>message])
```

I'm 99% sure that the reason is because arrow functions can't be bound in JavaScript (the whole reason they were introduced was to have 100% certainty that the value of `this` was correct, regardless of how the method was invoked). So when you use an arrow function, `this` doesn't refer to the correct Knockout object, it refers to something else since knockout wasn't able to bind the correct thing to `this`.

2019-03-29 19:35 UTC, travigd commented on src/Knockout.jl
> +js_lambda(s::String) = "=> $s"
Shouldn't this be `"() => $s"`?

2019-03-30 12:18 UTC, piever commented on src/Knockout.jl
> +js_lambda(s::String) = "=> $s"
Yes, I guess that'd be cleaner!

2019-03-30 12:28 UTC, piever commented
Actually, what happened is that Knockout is being updated to Knockout 4.0 and they switched from using anonymous functions to lambdas (there is some discussion here https://github.com/knockout/tko/issues/91). I confess I don't have a clear understanding of the lambda versus anonymous function difference, for more complicated things I think it is recommended to pass them to the Knockout model as `methods`.

If you build Knockout on this PR, it should download the correct Knockout javascript (4.0 alpha 8) and your snippet above should work. I still have not made up my mind whethere there is a good reason to update or not (the new codebase should be cleaner, smaller and more efficient but may be less tested than the old one).

2019-03-30 17:10 UTC, piever commented
The main drawback seems to be that nesting widgets stops working (we had the same problem with Vue.js which is why we moved to Knockout), for example:

```julia
julia> s = tabulator(OrderedDict("a" => checkbox("Asda"), "b" => slider(1:100)));
```

gives `Error: You cannot apply bindings multiple times to the same element`, so for sure better defer this till the nesting problem gets clarified.

2019-03-30 17:19 UTC, twavv approved these changes

2019-03-30 17:21 UTC, travigd commented
I remember getting that issue before when writing the new client side of WebIO. I think it had something to do with the order in which elements were constructed versus when scripts were run. It also might be possible that the way nested things work currently is just an implementation of Knockout? Do they support nested things?

2019-03-30 17:59 UTC, piever commented
I think they support that, I'm asking there how I can prevent a node from getting bindings from a model in a parent node (somehow that seemed to work out of the box before).

2019-03-30 18:34 UTC, piever commented
It seems that you can add this to the Knockout model and then you'd need to set `data-bind="allowBindings: false` in a node if you don't want the parent model to be applied there. Could we maybe even set this by default in all scopes from WebIO?

2019-03-30 18:46 UTC, travigd commented
I don't think that should happen in WebIO itself (at least in an ideal world) since it's specific to Knockout. Could you just wrap knockouts in a node that has that attribute?

2019-05-31 20:38 UTC, closed without merging